[alias]
b = "build -p solana-e"
c = "check -p solana-e"
d = "tree -d"

[build]
incremental = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
]
